APPLY_FIXES: all
ENABLE_LINTERS:
  - BASH_EXEC
  - BASH_SHELLCHECK
  - BASH_SHFMT
  - DOCKERFILE_DOCKERFILELINT
  - DOCKERFILE_HADOLINT
  - MARKDOWN_MARKDOWN_LINK_CHECK
  - MARKDOWN_MARKDOWN_TABLE_FORMATTER
  - MARKDOWN_MARKDOWNLINT
  - MARKDOWN_REMARK_LINT
  - YAML_YAMLLINT
  - YAML_PRETTIER
  - YAML_V8R
VALIDATE_ALL_CODEBASE: true
